prime_factors_kata/config/routes.rb
Rails.application.routes.draw do
  resources :numbers

end

prime_factors_kata/app/models/number.rb
class Number < ActiveRecord::Base
end

prime_factors_kata/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

prime_factors_kata/app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :set_number, only: [:show, :edit, :update, :destroy, :showprime]



  # GET /numbers
  # GET /numbers.json
  def index
    @numbers = Number.all
  end

  # GET /numbers/1
  # GET /numbers/1.json
  def show
  #@primefact = generate @number
  @primefact = generate @number.prime
  end

  

  # GET /numbers/new
  def new
    @number = Number.new
  end

  # GET /numbers/1/edit
  def edit
  end

  # POST /numbers
  # POST /numbers.json
  def create
    @number = Number.new(number_params)
    

    respond_to do |format|
      if @number.save
        format.html { redirect_to @number, notice: 'Number was successfully created.' }
        format.json { render :show, status: :created, location: @number }
      else
        format.html { render :new }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /numbers/1
  # PATCH/PUT /numbers/1.json
  def update
    respond_to do |format|
      if @number.update(number_params)
        format.html { redirect_to @number, notice: 'Number was successfully updated.' }
        format.json { render :show, status: :ok, location: @number }
      else
        format.html { render :edit }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end




  # DELETE /numbers/1
  # DELETE /numbers/1.json
  def destroy
    @number.destroy
    respond_to do |format|
      format.html { redirect_to numbers_url, notice: 'Number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_params
      params.require(:number).permit(:prime)
    end


    #Need fix here
    def generate(n)
    return n
    end


end

prime_factors_kata/app/helpers/application_helper.rb
module ApplicationHelper
end

prime_factors_kata/app/helpers/numbers_helper.rb
module NumbersHelper
end

prime_factors_kata/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimeFactorsKata</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

prime_factors_kata/app/views/numbers/_form.html.erb
<%= form_for(@number) do |f| %>
  <% if @number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
      <% @number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prime %><br>
    <%= f.number_field :prime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

prime_factors_kata/app/views/numbers/edit.html.erb
<h1>Editing number</h1>

<%= render 'form' %>

<%= link_to 'Show', @number %> |
<%= link_to 'Back', numbers_path %>

prime_factors_kata/app/views/numbers/index.html.erb
<h1>Prime Factors Katta !! </h1>

<table>
  <thead>
    <tr>
      <th>Prime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @numbers.each do |number| %>
      <tr>
        <td><%= number.prime %></td>
        <td><%= link_to 'Show Prime Factors', number %></td>
        <td><%= link_to 'Destroy', number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Number', new_number_path %>

prime_factors_kata/app/views/numbers/new.html.erb
<h1>Demo Version 1.2</h1>
<h1>New number</h1>

<%= render 'form' %>

<%= link_to 'Back', numbers_path %>

prime_factors_kata/app/views/numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prime Number :</strong>
  <%= @number.prime %>
 <br> Prime Factors :<%= @primefact %>
</p>

<%= link_to 'Edit', edit_number_path(@number) %> |
<%= link_to 'Back', numbers_path %>

prime_factors_kata/app/views/numbers/showprime.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prime Factors :</strong>
  <%= @number.prime %>
</p>

<%= link_to 'Edit', edit_number_path(@number) %> |
<%= link_to 'Back', numbers_path %>